### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by lukaswarce** [jonathanmarvens/atom-language-erlang#5] opened 2015-04-21 16:08 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (..\atom\app-0.192.0\resources\app\src\package.js:547:9)
<unknown> (..\atom\app-0.192.0\resources\app\src\package.js:168:43)
```

**Comment by optikfluffel** [comment] 2015-04-29 07:13
Duplicate of #4

**Closed** 2015-05-25 22:29 UTC
