### ISSUE TITLE
End of Directive Not Matched If It Contains fun()

### ISSUE THREAD

**Issue by bschug** [jonathanmarvens/atom-language-erlang#9] opened 2015-07-02 21:34 UTC
If a directive (e.g. -spec or -type) contains a fun(...) type definition, the grammar doesn't properly match the end of the directive and treats the entire rest of the file as being part of the directive. 

Example:

``` erlang
-module(test).

% this one works fine
-spec a() -> ok.
a() -> ok.

% this directive isn't matched correctly and will never end
-spec b( fun(() -> ok) ) -> not_ok.
b(F) -> not_ok.
```

**Comment by janl** [comment] 2017-03-09 09:57
Cannot reproduce anymore, might have been fixed in the meantime. Please re-open if you can show this again.

**Closed by janl** 2017-03-09 09:57 UTC
