### ISSUE TITLE
I can break syntax highlighter by placing a struct's close paren differently

### ISSUE THREAD

**Issue by chatterbeak** [jonathanmarvens/atom-language-erlang#16] opened 2016-03-22 17:47 UTC
See these two screenshots.

Here it's working:

![workingp](https://cloud.githubusercontent.com/assets/13056860/13961766/30de84ec-f01b-11e5-9ebd-b822e6cd54f4.png)

but if I move the closing paren on that record to a new line, syntax higlightling will not work at any point later in the file:

![brokenp](https://cloud.githubusercontent.com/assets/13056860/13961812/700a4a3e-f01b-11e5-98a8-0c8eda468f98.png)

I'm running 1.6.0 on a Mac.

**Comment by janl** [comment] 2017-03-09 10:05
confirmed, but is this a problem for you?

**Comment by janl** [comment] 2017-03-09 10:09
It looks like this a limitation in the grammar parser: https://github.com/atom/first-mate/issues/57

Closing, feel free to re-open when a solution presents itself.

**Closed by janl** 2017-03-09 10:09 UTC

**Comment by chatterbeak** [comment] 2017-03-09 20:01
Thanks. It's not a problem anymore because I switched to Visual Studio Code!
